name: Portfolio
description: Patrick Cate's Portfolio
markdown: kramdown
highlighter: pygments
relative_permalinks: true
doctor: true
url: http://portfolio.patrickcate.com

timezone:       America/New_York
source:         .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts
include: [
          '.htaccess',
          'jquery-1.11.2.min.js',
          'parsley-2.0.6.min.js',
          'scripts-*.min.js',
          'init-*.min.js'
         ]

# Serving
port: 3000
host: localhost

gems: [
    'jekyll_version_plugin',
    'jekyll/minibundle'
    ]

sitemap:
  file: '/sitemap.xml'

collections:
- project

exclude: [
    '*.json',
    '*.log',
    '*.map',
    '*.zip',
    'js/*.js',
    '*.sublime-project',
    '*.sublime-workspace',
    'config.rb',
    'Gemfile',
    'Gemfile.lock',
    'grunt',
    'Gruntfile.js',
    'gulpfile.js',
    'node_modules',
    'sass',
    # 'css/styles.css',
    # 'js/scripts.min.js'
]
