name: Portfolio
description: Patrick Cate's Portfolio
markdown: kramdown
highlighter: pygments
relative_permalinks: true
doctor: true
url: http://portfolio.patrickcate.com

timezone:       America/New_York
source:         .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts
include: [
          '.htaccess',
          'jquery-1.11.1.min.js',
          'parsley.min.js',
          'scripts.min.js',
          'respond.min.js'
         ]

# Serving
port: 3000
host: localhost

gems: [
    'jekyll_version_plugin'
    ]

sitemap:
  file: '/sitemap.xml'

picture:
  markup: 'picture'
  source: '_source/images'
  output: 'images'
  presets:
    default:
      ppi: [1, 1.5, 2.0]
      attr:
        class: "img"
      # source_large:
      #   width: '720'
      #   media: '(min-width: 720)'
      # source_medium:
      #   width: '640'
      #   media: '(min-width: 640px)'
      source_default:
        width: '640'

collections:
- project

exclude: [
    '*.json',
    '*.log',
    '*.map',
    '*.zip',
    'js/*.js',
    '*.sublime-project',
    '*.sublime-workspace',
    'config.rb',
    'Gemfile',
    'Gemfile.lock',
    'grunt',
    'Gruntfile.js',
    'gulpfile.js',
    'node_modules',
    'sass',
]